/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senaigo.locadora.view;

import br.com.senaigo.locadora.comunicacao.ServidorTcp;
import br.com.senaigo.locadora.controller.ServerTcpController;

/**
 *
 * @author pfellype
 */
public class TelaSelecaoAplicacao extends javax.swing.JFrame {

	/**
	 * Creates new form TelaSelecaoAplicacao
	 */
	public TelaSelecaoAplicacao() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanelBase = new javax.swing.JPanel();
		jPanelLogo = new javax.swing.JPanel();
		jLabelLogo = new javax.swing.JLabel();
		jButtonCliente = new javax.swing.JButton();
		jButtonServidor = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Rent System");
		setResizable(false);

		jPanelBase.setBackground(new java.awt.Color(255, 255, 255));
		jPanelBase.setForeground(new java.awt.Color(255, 255, 255));

		jPanelLogo.setBackground(new java.awt.Color(255, 204, 0));

		jLabelLogo.setIcon(new javax.swing.ImageIcon("/home/pfellype/NetBeansProjects/pi-locadora/arquivo/imagens/logoPI.png")); // NOI18N

		javax.swing.GroupLayout jPanelLogoLayout = new javax.swing.GroupLayout(jPanelLogo);
		jPanelLogo.setLayout(jPanelLogoLayout);
		jPanelLogoLayout.setHorizontalGroup(
			jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogoLayout.createSequentialGroup()
					.addContainerGap(100, Short.MAX_VALUE)
					.addComponent(jLabelLogo)
					.addGap(100, 100, 100))
		);
		jPanelLogoLayout.setVerticalGroup(
			jPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelLogoLayout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, Short.MAX_VALUE)
					.addGap(26, 26, 26))
		);

		jButtonCliente.setText("Rodar Aplicação Cliente");
		jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonClienteActionPerformed(evt);
			}
		});

		jButtonServidor.setText("Rodar Aplicação Servidor");
		jButtonServidor.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonServidorActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
		jPanelBase.setLayout(jPanelBaseLayout);
		jPanelBaseLayout.setHorizontalGroup(
			jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBaseLayout.createSequentialGroup()
					.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
						.addComponent(jButtonServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jButtonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addGap(110, 110, 110))
		);
		jPanelBaseLayout.setVerticalGroup(
			jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanelBaseLayout.createSequentialGroup()
					.addComponent(jPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					.addGap(32, 32, 32)
					.addComponent(jButtonCliente)
					.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
					.addComponent(jButtonServidor)
					.addGap(22, 22, 22))
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
		// TODO add your handling code here:
		TelaLogon tela = new TelaLogon();
		tela.setVisible(true);
		this.dispose();
	}//GEN-LAST:event_jButtonClienteActionPerformed

	private void jButtonServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServidorActionPerformed
		// TODO add your handling code here:
		this.dispose();
		try {
			ServidorTcp servidor = new ServidorTcp(7777);
			System.out.println("Servidor online.");
			while (true) {
				String requisicao = servidor.receberMensagem();
				System.out.println("Solicitação do cliente:" + requisicao);
				ServerTcpController controller = new ServerTcpController(requisicao);
				String resposta = controller.atendaRequisicao();
				servidor.enviarMensagem(resposta);
			}
		} catch (Exception e) {
			System.out.println("Erro no servidor: " + e.getMessage());
		}

	}//GEN-LAST:event_jButtonServidorActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(TelaSelecaoAplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(TelaSelecaoAplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(TelaSelecaoAplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(TelaSelecaoAplicacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaSelecaoAplicacao().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonCliente;
	private javax.swing.JButton jButtonServidor;
	private javax.swing.JLabel jLabelLogo;
	private javax.swing.JPanel jPanelBase;
	private javax.swing.JPanel jPanelLogo;
	// End of variables declaration//GEN-END:variables
}
